/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#006875',
        tertiary: '#e4edff',
        'secondary-fixed-dim': '#bec6e0',
        'on-tertiary-fixed-variant': '#3a485c',
        'on-primary': '#00363d',
        'on-tertiary': '#233144',
        'surface-container': '#1d2022',
        secondary: '#bec6e0',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#004f58',
        'inverse-surface': '#e0e3e5',
        'tertiary-container': '#c3d1ea',
        'primary-container': '#00e5ff',
        'outline-variant': '#3b494c',
        'on-secondary-fixed-variant': '#3f465c',
        outline: '#849396',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#b9c7e0',
        'surface-dim': '#101415',
        'on-error-container': '#ffdad6',
        primary: '#c3f5ff',
        'surface-container-high': '#272a2c',
        'error-container': '#93000a',
        'surface-container-highest': '#323537',
        'inverse-on-surface': '#2d3133',
        'on-primary-fixed': '#001f24',
        'secondary-fixed': '#dae2fd',
        'on-primary-container': '#00626e',
        'tertiary-fixed': '#d5e3fd',
        'surface-bright': '#363a3b',
        'surface-container-lowest': '#0b0f10',
        surface: '#101415',
        'primary-fixed': '#9cf0ff',
        'on-secondary-fixed': '#131b2e',
        'surface-variant': '#323537',
        'secondary-container': '#3f465c',
        'primary-fixed-dim': '#00daf3',
        'on-tertiary-fixed': '#0d1c2f',
        'on-background': '#e0e3e5',
        'surface-container-low': '#191c1e',
        'on-surface-variant': '#bac9cc',
        'on-secondary': '#283044',
        'on-secondary-container': '#adb4ce',
        background: '#101415',
        'surface-tint': '#00daf3',
        'on-surface': '#e0e3e5',
        'on-tertiary-container': '#4c5a6f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'panel-width-side': '280px',
        gutter: '16px',
        'margin-page': '24px',
        'panel-width-inspector': '320px',
        'radius-outer': '8px',
        'radius-inner': '4px',
        unit: '4px',
      },
      fontFamily: {
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md-mobile': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'label-numeric': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '1.4', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md-mobile': ['20px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-numeric': ['13px', { lineHeight: '1.0', letterSpacing: '0.02em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
